
from __future__ import annotations

from functools import lru_cache

from pydantic import computed_field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """
    Application configuration.

    All configuration values are loaded dynamically from
    environment variables / .env.

    Environment variables are case-insensitive because
    case_sensitive=False is enabled.
    """

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        case_sensitive=False,
        extra="ignore",
    )

    # =========================================================
    # Application
    # =========================================================

    app_name: str = "Zigma Voice Gmail Agent"

    app_version: str = "1.0.0"

    app_environment: str = "development"

    environment: str = "development"

    default_mode: str = "text"

    confidence_threshold: float = 0.70

    # =========================================================
    # Security
    # =========================================================

    jwt_secret_key: str = ""

    jwt_algorithm: str = "HS256"

    jwt_access_token_expire_minutes: int = 60

    # =========================================================
    # API
    # =========================================================

    api_host: str = "127.0.0.1"

    api_port: int = 8000

    debug: bool = False

    # =========================================================
    # AWS
    # =========================================================

    aws_region: str = ""

    aws_access_key_id: str = ""

    aws_secret_access_key: str = ""

    aws_secret_prefix: str = ""

    # =========================================================
    # Amazon Bedrock / LLM
    # =========================================================

    llm_provider: str = "bedrock"

    llm_model: str = ""

    llm_max_tokens: int = 1000

    llm_temperature: float = 0.1

    llm_top_p: float = 0.9

    # =========================================================
    # Google / Gmail OAuth
    # =========================================================

    google_client_id: str = ""

    google_client_secret: str = ""

    google_redirect_uri: str = ""

    google_gmail_scope: str = ""

    # =========================================================
    # Legacy Gmail configuration
    #
    # Kept for compatibility with existing modules.
    # =========================================================

    gmail_client_id: str = ""

    gmail_client_secret: str = ""

    gmail_redirect_uri: str = ""

    gmail_scope: str = ""

    gmail_default_page_size: int = 20

    gmail_max_page_size: int = 100

    # =========================================================
    # Speech
    # =========================================================

    stt_provider: str = ""

    tts_provider: str = ""

    supported_languages: str = "en,hi,ta,te,kn,ml"

    # =========================================================
    # Sarvam
    # =========================================================

    sarvam_api_key: str = ""

    sarvam_stt_model: str = ""

    sarvam_tts_model: str = ""

    sarvam_tts_language_code: str = ""

    sarvam_tts_speaker: str = ""

    # =========================================================
    # Database
    # =========================================================

    database_url: str = ""

    # =========================================================
    # Redis / Celery
    # =========================================================

    redis_url: str = ""

    celery_broker_url: str = ""

    celery_result_backend: str = ""

    # =========================================================
    # WebSocket
    # =========================================================

    websocket_enabled: bool = True

    # =========================================================
    # CORS
    # =========================================================

    cors_origins: str = ""

    # =========================================================
    # Email Formatting
    # =========================================================

    email_signature_enabled: bool = True

    email_signature: str = ""

    email_automated_note_enabled: bool = True

    email_automated_note: str = (
        "Note : This Email is automatically generated by the computer"
    )

    # =========================================================
    # Computed Values
    # =========================================================

    @computed_field
    @property
    def is_development(self) -> bool:
        """
        Return True when the application is running
        in development mode.
        """

        return self.environment.lower() == "development"

    @computed_field
    @property
    def supported_language_list(self) -> list[str]:
        """
        Convert the comma-separated language configuration
        into a clean list.
        """

        return [
            language.strip()
            for language in self.supported_languages.split(",")
            if language.strip()
        ]

    @computed_field
    @property
    def cors_origin_list(self) -> list[str]:
        """
        Convert comma-separated CORS origins into a list.
        """

        return [
            origin.strip()
            for origin in self.cors_origins.split(",")
            if origin.strip()
        ]


# =============================================================
# Cached Settings Factory
# =============================================================

@lru_cache
def get_settings() -> Settings:
    """
    Create and cache the application settings.

    The configuration is loaded from .env/environment variables.
    """

    return Settings()


# =============================================================
# Shared Settings Instance
# =============================================================

settings = get_settings()

