from __future__ import annotations

import json
from typing import Any

from app.agent.intent import (
    GmailIntent,
    GmailIntentRequest,
    MessageReferenceType,
)

from app.agent.bedrock import bedrock_service
from app.agent.state import (
    ConversationState,
    GmailResult,
    conversation_state,
)

from app.gmail.read import gmail_read_service
from app.gmail.reply import gmail_reply_service
from app.gmail.send import gmail_send_service
from app.gmail.draft import gmail_draft_service


# =============================================================
# Automatic generated-email note
# =============================================================

AUTO_REPLY_NOTE = (
    "Note: This email is automatically generated by computer."
)


class GmailExecutor:
    """
    Executes structured Gmail intents.

    The executor does NOT understand natural language.

    Natural-language understanding is performed by Bedrock
    before this class is called.

    Responsibilities
    ----------------
    - Execute structured Gmail operations.
    - Resolve semantic message references through
      ConversationState.
    - Preserve conversational context.
    - Remember sent and replied messages.
    - Use Gmail-generated message/thread/draft IDs.
    - Never generate Gmail IDs.
    - Never accept user-specific Gmail identifiers as
      application-generated values.
    - Require confirmation before destructive actions.

    Architecture
    ------------

        User language
             |
             v
        Bedrock / AI planner
             |
             v
        GmailIntentRequest
             |
             v
        GmailExecutor
             |
             v
        ConversationState
             |
             v
        Gmail services
             |
             v
        Gmail API

    Responsibilities by layer
    --------------------------

    Bedrock:
        Decides WHAT the user wants.

    ConversationState:
        Decides WHICH Gmail message/thread the user
        is referring to.

    GmailExecutor:
        Executes the structured operation.

    Gmail:
        Supplies actual:
            - message_id
            - thread_id
            - draft_id

    No user-specific Gmail information is hard-coded.
    """

    # =========================================================
    # INITIALIZATION
    # =========================================================

    def __init__(
        self,
        state: ConversationState | None = None,
    ) -> None:
        """
        Initialize the Gmail executor.

        A shared ConversationState instance is preferred so
        conversational context survives across requests.
        """

        self.state = (
            state
            if state is not None
            else conversation_state
        )

    # =========================================================
    # PUBLIC EXECUTE
    # =========================================================

    def execute(
        self,
        request: GmailIntentRequest,
        account_email: str | None = None,
    ) -> dict[str, Any]:
        """
        Execute a structured Gmail request.

        Parameters
        ----------
        request:
            Structured Gmail intent produced by the intent layer.

        account_email:
            Authenticated Gmail account supplied by the
            authentication/session layer.

        The LLM does not control the authenticated Gmail
        account.
        """

        # -----------------------------------------------------
        # Validate request
        # -----------------------------------------------------

        if not isinstance(
            request,
            GmailIntentRequest,
        ):
            raise TypeError(
                "request must be a GmailIntentRequest."
            )

        # -----------------------------------------------------
        # Store authenticated account
        # -----------------------------------------------------

        if account_email:

            cleaned_account = account_email.strip()

            if not cleaned_account:

                raise ValueError(
                    "Authenticated Gmail account cannot be empty."
                )

            self.state.set_account(
                cleaned_account
            )

        # -----------------------------------------------------
        # Resolve account
        # -----------------------------------------------------

        account = (
            account_email
            or self.state.account_email
        )

        if account:
            account = account.strip()

        if not account:

            raise ValueError(
                "Authenticated Gmail account is required."
            )

        # -----------------------------------------------------
        # Intent dispatch
        # -----------------------------------------------------

        handlers = {
            GmailIntent.SEARCH: self._search,
            GmailIntent.READ: self._read,
            GmailIntent.SEND: self._send,
            GmailIntent.DRAFT: self._draft,
            GmailIntent.REPLY: self._reply,
            GmailIntent.STAR: self._star,
            GmailIntent.UNSTAR: self._unstar,
            GmailIntent.DELETE: self._delete,
            GmailIntent.MARK_READ: self._mark_read,
            GmailIntent.MARK_UNREAD: self._mark_unread,
            GmailIntent.LIST_UNREAD: self._list_unread,
            GmailIntent.THREAD: self._thread,
        }

        handler = handlers.get(
            request.intent
        )

        if handler is None:

            raise ValueError(
                "Unsupported Gmail intent: "
                f"{request.intent.value}"
            )

        return handler(
            request=request,
            account_email=account,
        )

    # =========================================================
    # SEARCH
    # =========================================================

    def _search(
        self,
        request: GmailIntentRequest,
        account_email: str,
    ) -> dict[str, Any]:
        """
        Search or list Gmail messages.

        Query, result limit and account are resolved dynamically.
        """

        # -----------------------------------------------------
        # Resolve query
        # -----------------------------------------------------

        query = (
            request.query.strip()
            if request.query
            else None
        )

        # -----------------------------------------------------
        # Resolve result limit
        # -----------------------------------------------------

        max_results = (
            request.max_results
            if request.max_results is not None
            else None
        )

        if max_results is not None:

            if max_results <= 0:

                raise ValueError(
                    "max_results must be greater than zero."
                )

        # -----------------------------------------------------
        # Execute search
        # -----------------------------------------------------

        if query:

            result = gmail_read_service.search(
                account_email=account_email,
                query=query,
                max_results=max_results,
            )

        else:

            result = gmail_read_service.list_messages(
                account_email=account_email,
                query=None,
                max_results=max_results,
            )

        # -----------------------------------------------------
        # Extract results
        # -----------------------------------------------------

        messages = (
            result.get(
                "messages",
                [],
            )
            or []
        )

        next_page_token = result.get(
            "next_page_token"
        )

        # -----------------------------------------------------
        # Store results in conversation state
        # -----------------------------------------------------

        self.state.set_results(
            messages=messages,
            query=query,
            next_page_token=next_page_token,
        )

        # -----------------------------------------------------
        # Record action
        # -----------------------------------------------------

        self.state.record_action(
            action="search",
            details={
                "query": query,
                "result_count": len(messages),
            },
        )

        # -----------------------------------------------------
        # Return result
        # -----------------------------------------------------

        return {
            "success": True,
            "intent": GmailIntent.SEARCH.value,
            "query": query,
            "count": len(messages),
            "messages": messages,
            "next_page_token": next_page_token,
            "page": self.state.current_page,
        }

    # =========================================================
    # LIST UNREAD
    # =========================================================

    def _list_unread(
        self,
        request: GmailIntentRequest,
        account_email: str,
    ) -> dict[str, Any]:
        """
        List unread Gmail messages.

        The unread filter is represented using the standard
        Gmail search query:

            is:unread

        This method does not hard-code:
            - account
            - sender
            - recipient
            - subject
            - message ID
            - thread ID

        The query itself is an application-level semantic
        operation corresponding to the LIST_UNREAD intent.
        """

        # -----------------------------------------------------
        # Resolve result limit dynamically
        # -----------------------------------------------------

        max_results = (
            request.max_results
            if request.max_results is not None
            else None
        )

        if max_results is not None:

            if max_results <= 0:

                raise ValueError(
                    "max_results must be greater than zero."
                )

        # -----------------------------------------------------
        # Gmail unread query
        # -----------------------------------------------------

        query = "is:unread"

        # -----------------------------------------------------
        # Execute unread search
        # -----------------------------------------------------

        result = gmail_read_service.search(
            account_email=account_email,
            query=query,
            max_results=max_results,
        )

        # -----------------------------------------------------
        # Extract messages
        # -----------------------------------------------------

        messages = (
            result.get(
                "messages",
                [],
            )
            or []
        )

        next_page_token = result.get(
            "next_page_token"
        )

        # -----------------------------------------------------
        # Store unread results in conversation state
        # -----------------------------------------------------

        self.state.set_results(
            messages=messages,
            query=query,
            next_page_token=next_page_token,
        )

        # -----------------------------------------------------
        # Record action
        # -----------------------------------------------------

        self.state.record_action(
            action="list_unread",
            details={
                "query": query,
                "result_count": len(messages),
            },
        )

        # -----------------------------------------------------
        # Return result
        # -----------------------------------------------------

        return {
            "success": True,
            "intent": GmailIntent.LIST_UNREAD.value,
            "query": query,
            "count": len(messages),
            "messages": messages,
            "next_page_token": next_page_token,
            "page": self.state.current_page,
        }

    # =========================================================
    # READ
    # =========================================================

    def _read(
        self,
        request: GmailIntentRequest,
        account_email: str,
    ) -> dict[str, Any]:
        """
        Read a dynamically resolved Gmail message.
        """

        # -----------------------------------------------------
        # Resolve target message
        # -----------------------------------------------------

        result = self._resolve_message(
            request,
            account_email=account_email,
        )

        # -----------------------------------------------------
        # Retrieve complete Gmail message
        # -----------------------------------------------------

        message = gmail_read_service.get_message(
            account_email=account_email,
            message_id=result.message_id,
        )

        # -----------------------------------------------------
        # Make message current
        # -----------------------------------------------------

        self._select_result_object(
            result,
            message_data=message,
        )

        # -----------------------------------------------------
        # Record action
        # -----------------------------------------------------

        self.state.record_action(
            action="read",
            details={
                "message_id": result.message_id,
                "thread_id": result.thread_id,
            },
        )

        return {
            "success": True,
            "intent": GmailIntent.READ.value,
            "message": message,
            "message_id": result.message_id,
            "thread_id": result.thread_id,
        }

    # =========================================================
    # SEND
    # =========================================================

    def _send(
        self,
        request: GmailIntentRequest,
        account_email: str,
    ) -> dict[str, Any]:
        """
        Send a new Gmail message.

        Recipient, subject and body come from the structured
        request.

        Gmail generates message_id and thread_id.
        """

        # -----------------------------------------------------
        # Validate recipient
        # -----------------------------------------------------

        if not request.recipient:

            raise ValueError(
                "Recipient email address is required."
            )

        recipient = request.recipient.strip()

        if not recipient:

            raise ValueError(
                "Recipient email address is required."
            )

        # -----------------------------------------------------
        # Validate subject
        # -----------------------------------------------------

        if not request.subject:

            raise ValueError(
                "Email subject is required."
            )

        subject = request.subject.strip()

        if not subject:

            raise ValueError(
                "Email subject is required."
            )

        # -----------------------------------------------------
        # Validate body
        # -----------------------------------------------------

        if not request.body:

            raise ValueError(
                "Email body is required."
            )

        body = request.body.strip()

        if not body:

            raise ValueError(
                "Email body is required."
            )

        # -----------------------------------------------------
        # Add automatic generation note
        # -----------------------------------------------------

        send_body = (
            body.rstrip()
            + "\n\n"
            + AUTO_REPLY_NOTE
        )

        # -----------------------------------------------------
        # Preserve current Gmail context
        # -----------------------------------------------------

        self._preserve_current_context()

        # -----------------------------------------------------
        # Send email
        # -----------------------------------------------------

        result = gmail_send_service.send_email(
            account_email=account_email,
            recipient=recipient,
            subject=subject,
            body=send_body,
            cc=request.cc,
            bcc=request.bcc,
        )

        # -----------------------------------------------------
        # Gmail-generated identifiers
        # -----------------------------------------------------

        message_id = result.get(
            "message_id"
        )

        thread_id = result.get(
            "thread_id"
        )

        # -----------------------------------------------------
        # Store sent message context
        # -----------------------------------------------------

        self._set_generated_message_context(
            message_id=message_id,
            thread_id=thread_id,
            subject=subject,
            recipient=recipient,
            body=send_body,
            action="send",
            data=result,
        )

        # -----------------------------------------------------
        # Remember sent message
        # -----------------------------------------------------

        if message_id:

            self.state.remember_sent_message(
                message_id=message_id,
                thread_id=thread_id,
                recipient=recipient,
                subject=subject,
                body=send_body,
            )

        # -----------------------------------------------------
        # Record action
        # -----------------------------------------------------

        self.state.record_action(
            action="send",
            details={
                "message_id": message_id,
                "thread_id": thread_id,
                "recipient": recipient,
                "subject": subject,
            },
        )

        return {
            "success": True,
            "intent": GmailIntent.SEND.value,
            **result,
        }

    # =========================================================
    # DRAFT
    # =========================================================

    def _draft(
        self,
        request: GmailIntentRequest,
        account_email: str,
    ) -> dict[str, Any]:
        """
        Create a Gmail draft.

        The draft is created but not sent.
        """

        # -----------------------------------------------------
        # Validate recipient
        # -----------------------------------------------------

        if not request.recipient:

            raise ValueError(
                "Recipient email address is required."
            )

        recipient = request.recipient.strip()

        if not recipient:

            raise ValueError(
                "Recipient email address is required."
            )

        # -----------------------------------------------------
        # Validate subject
        # -----------------------------------------------------

        if not request.subject:

            raise ValueError(
                "Email subject is required."
            )

        subject = request.subject.strip()

        if not subject:

            raise ValueError(
                "Email subject is required."
            )

        # -----------------------------------------------------
        # Validate body
        # -----------------------------------------------------

        if not request.body:

            raise ValueError(
                "Email body is required."
            )

        body = request.body.strip()

        if not body:

            raise ValueError(
                "Email body is required."
            )

        # -----------------------------------------------------
        # Preserve current context
        # -----------------------------------------------------

        self._preserve_current_context()

        # -----------------------------------------------------
        # Create draft
        # -----------------------------------------------------

        result = gmail_draft_service.create_draft(
            account_email=account_email,
            recipient=recipient,
            subject=subject,
            body=body,
            cc=request.cc,
            bcc=request.bcc,
        )

        # -----------------------------------------------------
        # Gmail-generated identifiers
        # -----------------------------------------------------

        draft_id = result.get(
            "draft_id"
        )

        message_id = result.get(
            "message_id"
        )

        thread_id = result.get(
            "thread_id"
        )

        # -----------------------------------------------------
        # Store generated message context
        # -----------------------------------------------------

        if message_id:

            self._set_generated_message_context(
                message_id=message_id,
                thread_id=thread_id,
                subject=subject,
                recipient=recipient,
                body=body,
                action="draft",
                data=result,
            )

        # -----------------------------------------------------
        # Record action
        # -----------------------------------------------------

        self.state.record_action(
            action="draft",
            details={
                "draft_id": draft_id,
                "message_id": message_id,
                "thread_id": thread_id,
                "recipient": recipient,
                "subject": subject,
            },
        )

        return {
            "success": True,
            "intent": GmailIntent.DRAFT.value,
            **result,
        }

    # =========================================================
    # REPLY
    # =========================================================

    def _reply(
        self,
        request: GmailIntentRequest,
        account_email: str,
    ) -> dict[str, Any]:
        """
        Reply to a dynamically resolved Gmail message.
        """

        # -----------------------------------------------------
        # Resolve target message
        # -----------------------------------------------------

        result = self._resolve_message(
            request,
            account_email=account_email,
        )

        original_message_id = result.message_id
        original_thread_id = result.thread_id
        original_subject = result.subject
        original_recipient = result.recipient

        # -----------------------------------------------------
        # Generate the reply when the user did not provide text.
        #
        # "Reply to the second/that/this email" is a complete
        # request. The agent reads the actual Gmail message and
        # asks Bedrock to compose a context-aware reply.
        # If the user explicitly supplied reply text, that text
        # is preserved and sent instead.
        # -----------------------------------------------------

        reply_text = self._resolve_reply_body(
            request=request,
            result=result,
            account_email=account_email,
        )

        # -----------------------------------------------------
        # Add automatic generation note
        # -----------------------------------------------------

        reply_body = (
            reply_text.rstrip()
            + "\n\n"
            + AUTO_REPLY_NOTE
        )

        # -----------------------------------------------------
        # Send reply
        # -----------------------------------------------------

        reply_result = (
            gmail_reply_service.reply_to_message(
                account_email=account_email,
                message_id=original_message_id,
                body=reply_body,
            )
        )

        # -----------------------------------------------------
        # Gmail-generated reply identifiers
        # -----------------------------------------------------

        reply_message_id = reply_result.get(
            "message_id"
        )

        reply_thread_id = (
            reply_result.get(
                "thread_id"
            )
            or original_thread_id
        )

        # -----------------------------------------------------
        # Preserve original message context
        # -----------------------------------------------------

        self._select_result_object(
            result
        )

        # -----------------------------------------------------
        # Remember reply
        # -----------------------------------------------------

        self.state.remember_replied_message(
            original_message_id=original_message_id,
            reply_message_id=reply_message_id,
            thread_id=reply_thread_id,
            recipient=original_recipient,
            subject=original_subject,
            body=reply_body,
        )

        # -----------------------------------------------------
        # Reply becomes current context
        # -----------------------------------------------------

        if reply_message_id:

            self._set_generated_message_context(
                message_id=reply_message_id,
                thread_id=reply_thread_id,
                subject=original_subject,
                recipient=original_recipient,
                body=reply_body,
                action="reply",
                data=reply_result,
            )

        else:

            self.state.selected_thread_id = (
                reply_thread_id
            )

        # -----------------------------------------------------
        # Record action
        # -----------------------------------------------------

        self.state.record_action(
            action="reply",
            details={
                "original_message_id":
                    original_message_id,

                "reply_message_id":
                    reply_message_id,

                "thread_id":
                    reply_thread_id,

                "subject":
                    original_subject,
            },
        )

        return {
            "success": True,
            "intent": GmailIntent.REPLY.value,
            "original_message_id":
                original_message_id,
            "reply_message_id":
                reply_message_id,
            "thread_id":
                reply_thread_id,
            "reply":
                reply_result,
        }

    # =========================================================
    # REPLY BODY RESOLUTION
    # =========================================================

    def _resolve_reply_body(
        self,
        request: GmailIntentRequest,
        result: GmailResult,
        account_email: str,
    ) -> str:
        """
        Resolve the actual text to send in a reply.

        If the user supplied reply text, preserve it exactly
        (apart from surrounding whitespace).

        If the user only said something like:

            "Reply to the second mail"
            "Reply to that email"

        there is no missing information that should be requested
        from the user. The application retrieves the complete
        source email and Bedrock composes a context-aware reply.

        The LLM is allowed to generate only the reply text. It
        never generates Gmail message IDs, thread IDs, recipients,
        or any other Gmail identifier.
        """

        explicit_body = self._clean_reply_text(
            request.body
        )

        if explicit_body:
            return explicit_body

        if not result.message_id:
            raise ValueError(
                "The email to reply to could not be resolved."
            )

        # -----------------------------------------------------
        # Read the complete source email.
        # -----------------------------------------------------

        try:
            source_message = gmail_read_service.get_message(
                account_email=account_email,
                message_id=result.message_id,
            )
        except Exception as exc:
            raise RuntimeError(
                "I couldn't read the email before generating the reply."
            ) from exc

        source_data: dict[str, Any] = {}

        if isinstance(result.data, dict):
            source_data.update(result.data)

        if isinstance(source_message, dict):
            source_data.update(source_message)

        source_body = ConversationState._extract_body(
            source_data
        )

        # Some Gmail service implementations expose the body under
        # common alternate keys. Use them only when present; never
        # invent content.
        if not source_body:
            for key in (
                "body",
                "text",
                "content",
                "plain_text",
            ):
                value = source_data.get(key)
                if isinstance(value, str) and value.strip():
                    source_body = value.strip()
                    break

        sender = (
            source_data.get("from")
            or source_data.get("sender")
            or result.sender
        )

        recipient = (
            source_data.get("to")
            or source_data.get("recipient")
            or result.recipient
        )

        subject = (
            source_data.get("subject")
            or result.subject
        )

        date = (
            source_data.get("date")
            or result.date
        )

        snippet = (
            source_data.get("snippet")
            or result.snippet
        )

        # -----------------------------------------------------
        # Ask Bedrock to compose the reply from actual email data.
        # -----------------------------------------------------

        prompt = """
You are the autonomous reply-writing component of a production
Gmail AI assistant.

The user asked to reply to an existing email but did not provide
reply text. Therefore, compose the reply yourself using ONLY the
actual email content supplied below.

Your job is to write the email reply, not to explain what you did.
Return ONLY the reply text. Do not return JSON, markdown, labels,
analysis, or commentary.

Rules:
1. Understand the email before writing the reply.
2. Make the reply directly relevant to the email.
3. Be concise, natural, professional, and polite.
4. Do not invent facts, names, dates, meetings, amounts, files,
   promises, commitments, or decisions.
5. Do not claim that the user completed an action unless the
   source email or conversation explicitly establishes it.
6. If the email is informational, acknowledge it appropriately
   without inventing an opinion or commitment.
7. If the email asks a question, answer only when the answer is
   explicitly supported by the supplied context; otherwise give a
   safe acknowledgement rather than fabricating an answer.
8. If the email requests an action that cannot be determined from
   the supplied information, politely acknowledge the request
   without falsely promising completion.
9. Do not mention that you are an AI.
10. Do not mention Bedrock, prompts, Python, Gmail APIs, or
    internal application logic.
11. Do not include a subject line.
12. Do not include an automatic signature unless one is present
    in the supplied context.
13. Do not address a person by name unless that name is actually
    present in the supplied email data.
14. The output must be suitable for sending as the body of a
    Gmail reply.

ACTUAL EMAIL DATA:
"""

        payload = {
            "from": sender,
            "to": recipient,
            "subject": subject,
            "date": date,
            "body": source_body,
            "snippet": snippet,
        }

        prompt += json.dumps(
            payload,
            ensure_ascii=False,
            default=str,
        )

        try:
            response = bedrock_service.invoke(
                messages=[
                    {
                        "role": "user",
                        "content": [
                            {
                                "text": prompt
                            }
                        ],
                    }
                ],
                temperature=0.2,
            )
        except Exception as exc:
            raise RuntimeError(
                "I couldn't generate a reply from the email."
            ) from exc

        generated = self._extract_bedrock_text(
            response
        )

        if not generated:
            raise RuntimeError(
                "Bedrock returned an empty reply."
            )

        return generated

    @staticmethod
    def _clean_reply_text(
        value: Any,
    ) -> str:
        """Return explicit reply text when the user supplied it."""

        if value is None:
            return ""

        text = str(value).strip()

        if not text:
            return ""

        # Some intent parsers may emit null-like strings. Treat them
        # as missing instead of sending them to Gmail.
        if text.lower() in {
            "null",
            "none",
            "(missing)",
        }:
            return ""

        return text

    @staticmethod
    def _extract_bedrock_text(
        response: Any,
    ) -> str:
        """Extract plain text from common Bedrock service shapes."""

        if isinstance(response, str):
            return response.strip()

        if isinstance(response, dict):
            value = response.get("text")
            if value:
                return str(value).strip()

            content = response.get("content")
            if isinstance(content, list):
                parts: list[str] = []
                for item in content:
                    if not isinstance(item, dict):
                        continue
                    value = item.get("text")
                    if value:
                        parts.append(str(value))
                if parts:
                    return "\n".join(parts).strip()

        if isinstance(response, list):
            parts: list[str] = []
            for item in response:
                if not isinstance(item, dict):
                    continue
                value = item.get("text")
                if value:
                    parts.append(str(value))
            if parts:
                return "\n".join(parts).strip()

        return ""

    # =========================================================
    # STAR
    # =========================================================

    def _star(
        self,
        request: GmailIntentRequest,
        account_email: str,
    ) -> dict[str, Any]:
        """
        Star a dynamically resolved Gmail message.
        """

        result = self._resolve_message(
            request,
            account_email=account_email,
        )

        response = gmail_read_service.star_message(
            account_email=account_email,
            message_id=result.message_id,
        )

        self._select_result_object(
            result
        )

        self.state.record_action(
            action="star",
            details={
                "message_id":
                    result.message_id,

                "thread_id":
                    result.thread_id,
            },
        )

        return {
            "success": True,
            "intent": GmailIntent.STAR.value,
            **response,
        }

    # =========================================================
    # UNSTAR
    # =========================================================

    def _unstar(
        self,
        request: GmailIntentRequest,
        account_email: str,
    ) -> dict[str, Any]:
        """
        Remove the star from a dynamically resolved
        Gmail message.
        """

        result = self._resolve_message(
            request,
            account_email=account_email,
        )

        response = gmail_read_service.unstar_message(
            account_email=account_email,
            message_id=result.message_id,
        )

        self._select_result_object(
            result
        )

        self.state.record_action(
            action="unstar",
            details={
                "message_id":
                    result.message_id,

                "thread_id":
                    result.thread_id,
            },
        )

        return {
            "success": True,
            "intent": GmailIntent.UNSTAR.value,
            **response,
        }

    # =========================================================
    # DELETE
    # =========================================================

    def _delete(
        self,
        request: GmailIntentRequest,
        account_email: str,
    ) -> dict[str, Any]:
        """
        Prepare a delete operation.

        The message is NOT deleted immediately.

        The resolved Gmail message is stored as a pending
        destructive operation.
        """

        # -----------------------------------------------------
        # Resolve target message
        # -----------------------------------------------------

        result = self._resolve_message(
            request,
            account_email=account_email,
        )

        # -----------------------------------------------------
        # Make selected message current
        # -----------------------------------------------------

        self._select_result_object(
            result
        )

        # -----------------------------------------------------
        # Store pending delete
        # -----------------------------------------------------

        self.state.set_pending_delete(
            result=result,
            account_email=account_email,
        )

        # -----------------------------------------------------
        # Record confirmation requirement
        # -----------------------------------------------------

        self.state.record_action(
            action="delete_confirmation_required",
            details={
                "message_id":
                    result.message_id,

                "thread_id":
                    result.thread_id,

                "position":
                    result.position,

                "subject":
                    result.subject,

                "sender":
                    result.sender,
            },
        )

        # -----------------------------------------------------
        # Return confirmation request
        # -----------------------------------------------------

        return {
            "success": True,
            "intent": GmailIntent.DELETE.value,
            "confirmation_required": True,

            "message_id":
                result.message_id,

            "thread_id":
                result.thread_id,

            "position":
                result.position,

            "subject":
                result.subject,

            "sender":
                result.sender,
        }

    # =========================================================
    # CONFIRM PENDING DELETE
    # =========================================================

    def confirm_pending_delete(
        self,
        account_email: str | None = None,
    ) -> dict[str, Any]:
        """
        Execute a delete operation that was previously prepared.

        The message ID comes only from ConversationState.
        """

        # -----------------------------------------------------
        # Retrieve pending action
        # -----------------------------------------------------

        pending = (
            self.state.get_pending_action()
        )

        if not pending:

            raise ValueError(
                "There is no Gmail delete operation "
                "awaiting confirmation."
            )

        # -----------------------------------------------------
        # Verify pending action
        # -----------------------------------------------------

        if pending.get("action") != "delete":

            raise ValueError(
                "The pending operation is not "
                "a delete operation."
            )

        # -----------------------------------------------------
        # Resolve authenticated account
        # -----------------------------------------------------

        pending_account = pending.get(
            "account_email"
        )

        account = (
            account_email
            or pending_account
            or self.state.account_email
        )

        if account:
            account = account.strip()

        if not account:

            raise ValueError(
                "Authenticated Gmail account is required."
            )

        # -----------------------------------------------------
        # Resolve pending Gmail message ID
        # -----------------------------------------------------

        message_id = pending.get(
            "message_id"
        )

        if not message_id:

            self.state.clear_pending_action()

            raise ValueError(
                "The pending Gmail message "
                "could not be resolved."
            )

        thread_id = pending.get(
            "thread_id"
        )

        # -----------------------------------------------------
        # Execute Gmail trash operation
        # -----------------------------------------------------

        response = gmail_read_service.delete_message(
            account_email=account,
            message_id=message_id,
        )

        # -----------------------------------------------------
        # Clear pending operation
        # -----------------------------------------------------

        self.state.clear_pending_action()

        # -----------------------------------------------------
        # Record completed delete
        # -----------------------------------------------------

        self.state.record_action(
            action="delete",
            details={
                "message_id":
                    message_id,

                "thread_id":
                    thread_id,

                "subject":
                    pending.get(
                        "subject"
                    ),

                "sender":
                    pending.get(
                        "sender"
                    ),
            },
        )

        # -----------------------------------------------------
        # Return result
        # -----------------------------------------------------

        return {
            "success": True,
            "intent": GmailIntent.DELETE.value,
            "confirmation_required": False,

            "message_id":
                message_id,

            "thread_id":
                thread_id,

            "subject":
                pending.get(
                    "subject"
                ),

            "sender":
                pending.get(
                    "sender"
                ),

            **response,
        }

    # =========================================================
    # MARK READ
    # =========================================================

    def _mark_read(
        self,
        request: GmailIntentRequest,
        account_email: str,
    ) -> dict[str, Any]:
        """
        Mark a dynamically resolved message as read.
        """

        result = self._resolve_message(
            request,
            account_email=account_email,
        )

        response = gmail_read_service.mark_as_read(
            account_email=account_email,
            message_id=result.message_id,
        )

        self._select_result_object(
            result
        )

        self.state.record_action(
            action="mark_read",
            details={
                "message_id":
                    result.message_id,

                "thread_id":
                    result.thread_id,
            },
        )

        return {
            "success": True,
            "intent": GmailIntent.MARK_READ.value,
            **response,
        }

    # =========================================================
    # MARK UNREAD
    # =========================================================

    def _mark_unread(
        self,
        request: GmailIntentRequest,
        account_email: str,
    ) -> dict[str, Any]:
        """
        Mark a dynamically resolved message as unread.
        """

        result = self._resolve_message(
            request,
            account_email=account_email,
        )

        response = gmail_read_service.mark_as_unread(
            account_email=account_email,
            message_id=result.message_id,
        )

        self._select_result_object(
            result
        )

        self.state.record_action(
            action="mark_unread",
            details={
                "message_id":
                    result.message_id,

                "thread_id":
                    result.thread_id,
            },
        )

        return {
            "success": True,
            "intent": GmailIntent.MARK_UNREAD.value,
            **response,
        }

    # =========================================================
    # THREAD
    # =========================================================

    def _thread(
        self,
        request: GmailIntentRequest,
        account_email: str,
    ) -> dict[str, Any]:
        """
        Retrieve a complete Gmail conversation thread.
        """

        result = self._resolve_thread_message(
            request,
            account_email=account_email,
        )

        # -----------------------------------------------------
        # Thread ID must come from Gmail/state
        # -----------------------------------------------------

        if not result.thread_id:

            raise ValueError(
                "The selected Gmail message "
                "does not contain a thread ID."
            )

        # -----------------------------------------------------
        # Retrieve thread
        # -----------------------------------------------------

        thread = gmail_read_service.get_thread(
            account_email=account_email,
            thread_id=result.thread_id,
        )

        # -----------------------------------------------------
        # Make selected message current
        # -----------------------------------------------------

        self._select_result_object(
            result
        )

        # -----------------------------------------------------
        # Record action
        # -----------------------------------------------------

        self.state.record_action(
            action="thread",
            details={
                "message_id":
                    result.message_id,

                "thread_id":
                    result.thread_id,
            },
        )

        return {
            "success": True,
            "intent": GmailIntent.THREAD.value,

            "message_id":
                result.message_id,

            "thread_id":
                result.thread_id,

            "thread":
                thread,
        }

    # =========================================================
    # RESOLVE LATEST MESSAGE
    # =========================================================

    def _resolve_latest_message(
        self,
        account_email: str,
    ) -> GmailResult:
        """
        Resolve the latest email dynamically.

        Resolution order:

            1. Existing conversational result.
            2. Dynamically query Gmail for latest message.
        """

        # -----------------------------------------------------
        # Prefer current conversational result
        # -----------------------------------------------------

        latest = self.state.get_latest_result()

        if latest:
            return latest

        # -----------------------------------------------------
        # Query Gmail dynamically
        # -----------------------------------------------------

        response = gmail_read_service.list_messages(
            account_email=account_email,
            query=None,
            max_results=1,
        )

        messages = (
            response.get(
                "messages",
                [],
            )
            or []
        )

        if not messages:

            raise ValueError(
                "There is no email available."
            )

        # -----------------------------------------------------
        # Store retrieved message
        # -----------------------------------------------------

        self.state.set_results(
            messages=messages,
            query=None,
            next_page_token=response.get(
                "next_page_token"
            ),
        )

        # -----------------------------------------------------
        # Resolve latest from state
        # -----------------------------------------------------

        latest = self.state.get_latest_result()

        if not latest:

            raise ValueError(
                "Gmail returned an email but it could "
                "not be stored in conversation state."
            )

        return latest

    # =========================================================
    # RESOLVE MESSAGE
    # =========================================================

    def _resolve_message(
        self,
        request: GmailIntentRequest,
        account_email: str | None = None,
    ) -> GmailResult:
        """
        Resolve a semantic Gmail message reference.

        Supported reference types include:

            POSITION
            CURRENT
            PREVIOUS
            LATEST
            RAW / generic semantic reference

        Gmail IDs are never generated by this method.
        """

        reference = getattr(
            request,
            "message_reference",
            None,
        )

        account = (
            account_email
            or self.state.account_email
        )

        if account:
            account = account.strip()

        # =====================================================
        # No message reference object
        # =====================================================

        if reference is None:

            return self.state.resolve_message()

        # =====================================================
        # POSITION
        # =====================================================

        if (
            reference.type
            == MessageReferenceType.POSITION
        ):

            if reference.position is None:

                raise ValueError(
                    "Message position is missing."
                )

            position = reference.position

            if position <= 0:

                raise ValueError(
                    "Message position must be greater than zero."
                )

            if not account:

                raise ValueError(
                    "Authenticated Gmail account is required."
                )

            # -------------------------------------------------
            # Load enough messages if state is empty
            # -------------------------------------------------

            if not self.state.current_results:

                response = gmail_read_service.list_messages(
                    account_email=account,
                    query=None,
                    max_results=position,
                )

                messages = (
                    response.get(
                        "messages",
                        [],
                    )
                    or []
                )

                if not messages:

                    raise ValueError(
                        "There are no emails available."
                    )

                if len(messages) < position:

                    raise ValueError(
                        f"Only {len(messages)} email(s) "
                        "are available for the requested position."
                    )

                self.state.set_results(
                    messages=messages,
                    query=None,
                    next_page_token=response.get(
                        "next_page_token"
                    ),
                )

            return self.state.resolve_message(
                position=position
            )

        # =====================================================
        # CURRENT
        # =====================================================

        if (
            reference.type
            == MessageReferenceType.CURRENT
        ):

            return self.state.resolve_message(
                reference="current"
            )

        # =====================================================
        # PREVIOUS
        # =====================================================

        if (
            reference.type
            == MessageReferenceType.PREVIOUS
        ):

            return self.state.resolve_message(
                reference="previous"
            )

        # =====================================================
        # LATEST
        # =====================================================

        if (
            reference.type
            == MessageReferenceType.LATEST
        ):

            if not account:

                raise ValueError(
                    "Authenticated Gmail account is required."
                )

            try:

                return self.state.resolve_message(
                    reference="latest"
                )

            except ValueError:

                return self._resolve_latest_message(
                    account_email=account
                )

        # =====================================================
        # GENERIC / RAW REFERENCE
        # =====================================================

        raw_reference = getattr(
            reference,
            "raw",
            None,
        )

        if not raw_reference:

            return self.state.resolve_message()

        return self.state.resolve_message(
            reference=raw_reference
        )

    # =========================================================
    # RESOLVE THREAD MESSAGE
    # =========================================================

    def _resolve_thread_message(
        self,
        request: GmailIntentRequest,
        account_email: str | None = None,
    ) -> GmailResult:
        """
        Resolve the Gmail message whose thread should be opened.

        Thread IDs always come from Gmail/state.
        """

        # -----------------------------------------------------
        # Explicit thread reference
        # -----------------------------------------------------

        thread_reference = getattr(
            request,
            "thread_reference",
            None,
        )

        if (
            thread_reference is not None
            and thread_reference.is_present()
        ):

            temporary_request = GmailIntentRequest(
                intent=GmailIntent.THREAD,
                message_reference=thread_reference,
            )

            return self._resolve_message(
                temporary_request,
                account_email=account_email,
            )

        # -----------------------------------------------------
        # Message reference identifies the thread
        # -----------------------------------------------------

        message_reference = getattr(
            request,
            "message_reference",
            None,
        )

        if (
            message_reference is not None
            and message_reference.is_present()
        ):

            return self._resolve_message(
                request,
                account_email=account_email,
            )

        # -----------------------------------------------------
        # Otherwise use current selection
        # -----------------------------------------------------

        return self.state.resolve_message()

    # =========================================================
    # PRESERVE CURRENT CONTEXT
    # =========================================================

    def _preserve_current_context(
        self,
    ) -> None:
        """
        Preserve the current Gmail selection before an operation
        changes conversational context.
        """

        # -----------------------------------------------------
        # Prefer complete current message context
        # -----------------------------------------------------

        if self.state.current_message_context:

            self.state.previous_message_context = (
                dict(
                    self.state.current_message_context
                )
            )

            self.state.previous_message_id = (
                self.state.current_message_context.get(
                    "message_id"
                )
            )

            self.state.previous_thread_id = (
                self.state.current_message_context.get(
                    "thread_id"
                )
            )

        # -----------------------------------------------------
        # Fallback to selected identifiers
        # -----------------------------------------------------

        elif self.state.selected_message_id:

            self.state.previous_message_id = (
                self.state.selected_message_id
            )

            self.state.previous_thread_id = (
                self.state.selected_thread_id
            )

    # =========================================================
    # SET GENERATED MESSAGE CONTEXT
    # =========================================================

    def _set_generated_message_context(
        self,
        message_id: str | None,
        thread_id: str | None,
        subject: str | None = None,
        recipient: str | None = None,
        body: str | None = None,
        action: str = "select",
        data: dict[str, Any] | None = None,
    ) -> None:
        """
        Store a Gmail-generated message as current context.

        Used after:

            - SEND
            - DRAFT
            - REPLY

        Gmail supplies the actual identifiers.
        """

        # -----------------------------------------------------
        # Gmail must provide message ID
        # -----------------------------------------------------

        if not message_id:
            return

        # -----------------------------------------------------
        # Set selected identifiers
        # -----------------------------------------------------

        self.state.selected_message_id = (
            message_id
        )

        if thread_id:

            self.state.selected_thread_id = (
                thread_id
            )

        # -----------------------------------------------------
        # Build conversational context
        # -----------------------------------------------------

        context: dict[str, Any] = {
            "message_id":
                message_id,

            "thread_id":
                thread_id,

            "subject":
                subject,

            "sender":
                None,

            "recipient":
                recipient,

            "snippet":
                None,

            "date":
                None,

            "body":
                body or "",

            "action":
                action,

            "data":
                dict(data)
                if isinstance(
                    data,
                    dict,
                )
                else {},
        }

        # -----------------------------------------------------
        # Store current context
        # -----------------------------------------------------

        self.state.current_message_context = (
            context
        )

        # -----------------------------------------------------
        # Store latest action
        # -----------------------------------------------------

        self.state.last_action = action

    # =========================================================
    # SELECT RESULT OBJECT
    # =========================================================

    def _select_result_object(
        self,
        result: GmailResult,
        message_data: dict[str, Any] | None = None,
    ) -> None:
        """
        Make a Gmail result the current conversational selection.

        This preserves previous context and stores the selected
        message as current context.
        """

        # -----------------------------------------------------
        # Validate result
        # -----------------------------------------------------

        if not result:

            raise ValueError(
                "A Gmail result is required for selection."
            )

        if not result.message_id:

            raise ValueError(
                "A valid Gmail message is required for selection."
            )

        # -----------------------------------------------------
        # Preserve existing context
        # -----------------------------------------------------

        self._preserve_current_context()

        # -----------------------------------------------------
        # Set current selected message
        # -----------------------------------------------------

        self.state.selected_message_id = (
            result.message_id
        )

        self.state.selected_thread_id = (
            result.thread_id
        )

        # -----------------------------------------------------
        # Build combined message data
        # -----------------------------------------------------

        data: dict[str, Any] = {}

        if isinstance(
            result.data,
            dict,
        ):

            data.update(
                result.data
            )

        if isinstance(
            message_data,
            dict,
        ):

            data.update(
                message_data
            )

        # -----------------------------------------------------
        # Store complete conversational context
        # -----------------------------------------------------

        self.state.current_message_context = {
            "message_id":
                result.message_id,

            "thread_id":
                result.thread_id,

            "subject":
                result.subject,

            "sender":
                result.sender,

            "recipient":
                result.recipient,

            "snippet":
                result.snippet,

            "date":
                result.date,

            "body":
                ConversationState._extract_body(
                    data
                ),

            "action":
                "select",

            "data":
                dict(data),
        }

        # -----------------------------------------------------
        # Remember latest action
        # -----------------------------------------------------

        self.state.last_action = (
            "select_email"
        )


# =============================================================
# SHARED EXECUTOR
# =============================================================

gmail_executor = GmailExecutor(
    state=conversation_state
)